json_file: "example.js"  # Tweets JSON file path
output_dir: "output"  # Output directory
users_dir: "output/users"  # Output directory

# Turning off any of the properties by making it false
properties:
  include_retweets: false
  create_user_files: true
  attachments: true  # Image handling